# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='duties',
        ),
        migrations.RemoveField(
            model_name='career',
            name='learning_path',
        ),
        migrations.RemoveField(
            model_name='career',
            name='work_environment',
        ),
    ]
