# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_auto_20171230_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='category',
        ),
    ]
