# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_remove_career_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
