# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_auto_20171230_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='category',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='careers.Category'),
        ),
        migrations.AlterField(
            model_name='career',
            name='id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
