# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0006_auto_20171230_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='careers.Category'),
        ),
        migrations.AlterField(
            model_name='career',
            name='id',
            field=models.CharField(db_index=True, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
