# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-01 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0007_auto_20171231_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
