# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-01 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0008_auto_20180101_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('task', models.TextField(blank=True)),
                ('task_type', models.CharField(max_length=200)),
                ('career', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='careers.Career')),
            ],
        ),
    ]
