# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-01 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0009_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
