# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 08:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('careers', '0011_auto_20180101_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='careers_upvoted', to=settings.AUTH_USER_MODEL),
        ),
    ]
